var animalsArray = [
	{
		"image":"./imgs/ant.png",
		"name":"ant",
		"voice":"./img/audioanimal/ant.mp3"
	},		
	{
		"image":"./imgs/bear.png",
		"name":"bear",
		"voice":"./img/audioanimal/bear.mp3"
    },
    {
		"image":"./imgs/bee.png",
		"name":"bee",
		"voice":"./img/audioanimal/bee.mp3"
    },
    {
		"image":"./imgs/bird.png",
		"name":"bird",
		"voice":"./img/audioanimal/bird.mp3"
	},
	{
		"image":"./imgs/butterfly.png",
		"name":"butterfly",
		"voice":"./img/audioanimal/butterfly.mp3"
	},
	{
		"image":"./imgs/camel.png",
		"name":"camel",
		"voice":"./img/audioanimal/camel.mp3"
	},
	{
		"image":"./imgs/cat.png",
		"name":"cat",
		"voice":"./img/audioanimal/cat.mp3"
	},
	{
		"image":"./imgs/caterpillar.png",
		"name":"caterpillar",
		"voice":"./img/audioanimal/caterpillar.mp3"
	},
	{
		"image":"./imgs/chicken.png",
		"name":"chicken",
		"voice":"./img/audioanimal/chicken.mp3"
	},
	{
		"image":"./imgs/cow.png",
		"name":"cow",
		"voice":"./img/audioanimal/cow.mp3"
	},
	{
		"image":"./imgs/crab.png",
		"name":"crab",
		"voice":"./img/audioanimal/crab.mp3"
	},
	{
		"image":"./imgs/crocodile.png",
		"name":"crocodile",
		"voice":"./img/audioanimal/crocodile.mp3"
	},
	{
		"image":"./imgs/deer.png",
		"name":"deer",
		"voice":"./img/audioanimal/deer.mp3"
	},
	{
		"image":"./imgs/dog.png",
		"name":"dog",
		"voice":"./img/audioanimal/dog.mp3"
	},
	{
		"image":"./imgs/donkey.png",
		"name":"donkey",
		"voice":"./img/audioanimal/donkey.mp3"
	},
	{
		"image":"./imgs/duck.png",
		"name":"duck",
		"voice":"./img/audioanimal/duck.mp3"
	},
	{
		"image":"./imgs/elephant.png",
		"name":"elephant",
		"voice":"./img/audioanimal/elephant.mp3"
	},
	{
		"image":"./imgs/fish.png",
		"name":"fish",
		"voice":"./img/audioanimal/fish.mp3"
	},
	{
		"image":"./imgs/frog.png",
		"name":"frog",
		"voice":"./img/audioanimal/frog.mp3"
	},
	{
		"image":"./imgs/giraffe.png",
		"name":"giraffe",
		"voice":"./img/audioanimal/giraffe.mp3"
	},
	{
		"image":"./imgs/goat.png",
		"name":"goat",
		"voice":"./img/audioanimal/goat.mp3"
	},
	{
		"image":"./imgs/hamster.png",
		"name":"hamster",
		"voice":"./img/audioanimal/hamster.mp3"
	},
	{
		"image":"./imgs/hedgehog.png",
		"name":"hedgehog",
		"voice":"./img/audioanimal/hedgehog.mp3"
	},
	{
		"image":"./imgs/horse.png",
		"name":"horse",
		"voice":"./img/audioanimal/horse.mp3"
	},
	{
		"image":"./imgs/jellyfish.png",
		"name":"jellyfish",
		"voice":"./img/audioanimal/jellyfish.mp3"
	},
	{
		"image":"./imgs/ladybird.png",
		"name":"ladybird",
		"voice":"./img/audioanimal/ladybird.mp3"
	},
	{
		"image":"./imgs/sheep.png",
		"name":"sheep",
		"voice":"./img/audioanimal/sheep.mp3"
	},
	{
		"image":"./imgs/lion.png",
		"name":"lion",
		"voice":"./img/audioanimal/lion.mp3"
	},
	{
		"image":"./imgs/mole.png",
		"name":"mole",
		"voice":"./img/audioanimal/mole.mp3"
	},
	{
		"image":"./imgs/monkey.png",
		"name":"monkey",
		"voice":"./img/audioanimal/monkey.mp3"
	},
	{
		"image":"./imgs/mouse.png",
		"name":"mouse",
		"voice":"./img/audioanimal/mouse.mp3"
	},
	{
		"image":"./imgs/octopus.png",
		"name":"octopus",
		"voice":"./img/audioanimal/octopus.mp3"
	},
	{
		"image":"./imgs/owl.png",
		"name":"owl",
		"voice":"./img/audioanimal/owl.mp3"
	},
	{
		"image":"./imgs/panda.png",
		"name":"panda",
		"voice":"./img/audioanimal/panda.mp3"
	},
	{
		"image":"./imgs/penguin.png",
		"name":"penguin",
		"voice":"./img/audioanimal/penguin.mp3"
	},
	{
		"image":"./imgs/pig.png",
		"name":"pig",
		"voice":"./img/audioanimal/pig.mp3"
	},
	{
		"image":"./imgs/pony.png",
		"name":"pony",
		"voice":"./img/audioanimal/pony.mp3"
	},
	{
		"image":"./imgs/rabbit.png",
		"name":"rabbit",
		"voice":"./img/audioanimal/rabbit.mp3"
	},
	{
		"image":"./imgs/seahorse.png",
		"name":"seahorse",
		"voice":"./img/audioanimal/seahorse.mp3"
	},
	{
		"image":"./imgs/snake.png",
		"name":"snake",
		"voice":"./img/audioanimal/snake.mp3"
	},
	{
		"image":"./imgs/spider.png",
		"name":"spider",
		"voice":"./img/audioanimal/spider.mp3"
	},
	{
		"image":"./imgs/starfish.png",
		"name":"starfish",
		"voice":"./img/audioanimal/starfish.mp3"
	},
	{
		"image":"./imgs/stingray.png",
		"name":"stingray",
		"voice":"./img/audioanimal/stingray.mp3"
	},
	{
		"image":"./imgs/tiger.png",
		"name":"tiger",
		"voice":"./img/audioanimal/tiger.mp3"
	},
	{
		"image":"./imgs/turkey.png",
		"name":"turkey",
		"voice":"./img/audioanimal/turkey.mp3"
	},
	{
		"image":"./imgs/turtle.png",
		"name":"turtle",
		"voice":"./img/audioanimal/turtle.mp3"
	},
	{
		"image":"./imgs/unicorn.png",
		"name":"unicorn",
		"voice":"./img/audioanimal/unicorn.mp3"
	},
	{
		"image":"./imgs/whale.png",
		"name":"whale",
		"voice":"./img/audioanimal/whale.mp3"
	},
	{
		"image":"./imgs/worm.png",
		"name":"worm",
		"voice":"./img/audioanimal/worm.mp3"
	},
	{
		"image":"./imgs/zebra.png",
		"name":"zebra",
		"voice":"./img/audioanimal/zebra.mp3"
	},
	{
		"image":"./imgs/pigeon.png",
		"name":"pigeon",
		"voice":"./img/audioanimal/pigeon.mp3"
	},
	{
		"image":"./imgs/dinosaur.png",
		"name":"dinosaur",
		"voice":"./img/audioanimal/dinosaur.mp3"
	},
	{
		"image":"./imgs/dragon.png",
		"name":"dragon",
		"voice":"./img/audioanimal/dragon.mp3"
	},
	{
		"image":"./imgs/kangaroo.png",
		"name":"kangaroo",
		"voice":"./img/audioanimal/kangaroo.mp3"
	},
	{
		"image":"./imgs/clownfish.png",
		"name":"clownfish",
		"voice":"./img/audioanimal/clownfish.mp3"
	},
	{
		"image":"./imgs/rhinoceros.png",
		"name":"rhinoceros",
		"voice":"./img/audioanimal/rhinoceros.mp3"
	},
	{
		"image":"./imgs/toad.png",
		"name":"toad",
		"voice":"./img/audioanimal/toad.mp3"
	},
	{
		"image":"./imgs/puppy.png",
		"name":"puppy",
		"voice":"./img/audioanimal/puppy.mp3"
	},
	{
		"image":"./imgs/hippo.png",
		"name":"hippo",
		"voice":"./img/audioanimal/hippo.mp3"
	},
	{
		"image":"./imgs/rat.png",
		"name":"rat",
		"voice":"./img/audioanimal/rat.mp3"
	},
	{
		"image":"./imgs/ostrich.png",
		"name":"ostrich",
		"voice":"./img/audioanimal/ostrich.mp3"
	},
	{
		"image":"./imgs/peacock.png",
		"name":"peacock",
		"voice":"./img/audioanimal/peacock.mp3"
	}
];
function playAudio(i) {
	var url = animalsArray[i]["voice"];
	console.log('hello');
	new Audio(url).play();
  }
  function animals() {
	$('#div4').html('');
	var $title = $('<h1 class = "titleh2">Pick an animal and learn how to spell its name</h1>')
	$('#div4').append($title);
	var $animals =  $('<div id="colors" class="row animalslist"></div>');
	var index = animalsArray.length - 1;
    while(index >= 0){
		var audio = animalsArray[index]["voice"];
		console.log(audio);
		var $animal = $('<div class=" column"><img id="'+index+'"onclick="playAudio(this.id)" style="background-color : white" class=" imggame animal" src="'+animalsArray[index]["image"]+'" alt="Colors" ></div>');
		var $text = $('<h2 class="animalname">'+animalsArray[index]["name"]+'</h2>');
		$animal.append($text);
		$animals.prepend($animal);
		index--;
	}

	$('#div4').append($animals);
}  
