export var animalsArray = [
	{
		"image":"./imgs/ant.png",
		"name":"ant",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_ant_word.mp3"
	},		
	{
		"image":"./imgs/bear.png",
		"name":"bear",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_bear_word.mp3"
    },
    {
		"image":"./imgs/bee.png",
		"name":"bee",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_bee_word.mp3"
    },
    {
		"image":"./imgs/bird.png",
		"name":"bird",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_bird_word.mp3"
	},
	{
		"image":"./imgs/butterfly.png",
		"name":"butterfly",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_butterfly_word.mp3"
	},
	{
		"image":"./imgs/camel.png",
		"name":"camel",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_camel_word.mp3"
	},
	{
		"image":"./imgs/cat.png",
		"name":"cat",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_cat_word.mp3"
	},
	{
		"image":"./imgs/caterpillar.png",
		"name":"caterpillar",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_caterpillar_word.mp3"
	},
	{
		"image":"./imgs/chicken.png",
		"name":"chicken",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_chicken_word.mp3"
	},
	{
		"image":"./imgs/cow.png",
		"name":"cow",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_cow_word.mp3"
	},
	{
		"image":"./imgs/crab.png",
		"name":"crab",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_crab_word.mp3"
	},
	{
		"image":"./imgs/crocodile.png",
		"name":"crocodile",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_crocodile_word.mp3"
	},
	{
		"image":"./imgs/deer.png",
		"name":"deer",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_deer_word.mp3"
	},
	{
		"image":"./imgs/dog.png",
		"name":"dog",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_dog_word.mp3"
	},
	{
		"image":"./imgs/donkey.png",
		"name":"donkey",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_donkey_word.mp3"
	},
	{
		"image":"./imgs/duck.png",
		"name":"duck",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_duck_word.mp3"
	},
	{
		"image":"./imgs/elephant.png",
		"name":"elephant",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_elephant_word.mp3"
	},
	{
		"image":"./imgs/fish.png",
		"name":"fish",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_fish_word.mp3"
	},
	{
		"image":"./imgs/frog.png",
		"name":"frog",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_frog_word.mp3"
	},
	{
		"image":"./imgs/giraffe.png",
		"name":"giraffe",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_giraffe_word.mp3"
	},
	{
		"image":"./imgs/goat.png",
		"name":"goat",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_goat_word.mp3"
	},
	{
		"image":"./imgs/hamster.png",
		"name":"hamster",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_hamster_word.mp3"
	},
	{
		"image":"./imgs/hedgehog.png",
		"name":"hedgehog",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_hedgehog_word.mp3"
	},
	{
		"image":"./imgs/horse.png",
		"name":"horse",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_horse_word.mp3"
	},
	{
		"image":"./imgs/jellyfish.png",
		"name":"jellyfish",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_jellyfish_word.mp3"
	},
	{
		"image":"./imgs/ladybird.png",
		"name":"ladybird",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_ladybird_word.mp3"
	},
	{
		"image":"./imgs/sheep.png",
		"name":"sheep",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_sheep_word.mp3"
	},
	{
		"image":"./imgs/lion.png",
		"name":"lion",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_lion_word.mp3"
	},
	{
		"image":"./imgs/mole.png",
		"name":"mole",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_mole_word.mp3"
	},
	{
		"image":"./imgs/monkey.png",
		"name":"monkey",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_monkey_word.mp3"
	},
	{
		"image":"./imgs/mouse.png",
		"name":"mouse",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_mouse_word.mp3"
	},
	{
		"image":"./imgs/octopus.png",
		"name":"octopus",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_octopus_word.mp3"
	},
	{
		"image":"./imgs/owl.png",
		"name":"owl",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_owl_word.mp3"
	},
	{
		"image":"./imgs/panda.png",
		"name":"panda",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_panda_word.mp3"
	},
	{
		"image":"./imgs/penguin.png",
		"name":"penguin",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_penguin_word.mp3"
	},
	{
		"image":"./imgs/pig.png",
		"name":"pig",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_pig_word.mp3"
	},
	{
		"image":"./imgs/pony.png",
		"name":"pony",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_pony_word.mp3"
	},
	{
		"image":"./imgs/rabbit.png",
		"name":"rabbit",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_rabbit_word.mp3"
	},
	{
		"image":"./imgs/seahorse.png",
		"name":"seahorse",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_seahorse_word.mp3"
	},
	{
		"image":"./imgs/snake.png",
		"name":"snake",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_snake_word.mp3"
	},
	{
		"image":"./imgs/spider.png",
		"name":"spider",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_spider_word.mp3"
	},
	{
		"image":"./imgs/starfish.png",
		"name":"starfish",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_starfish_word.mp3"
	},
	{
		"image":"./imgs/stingray.png",
		"name":"stingray",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_stingray_word.mp3"
	},
	{
		"image":"./imgs/tiger.png",
		"name":"tiger",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_tiger_word.mp3"
	},
	{
		"image":"./imgs/turkey.png",
		"name":"turkey",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_turkey_word.mp3"
	},
	{
		"image":"./imgs/turtle.png",
		"name":"turtle",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_turtle_word.mp3"
	},
	{
		"image":"./imgs/unicorn.png",
		"name":"unicorn",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_unicorn_word.mp3"
	},
	{
		"image":"./imgs/whale.png",
		"name":"whale",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_whale_word.mp3"
	},
	{
		"image":"./imgs/worm.png",
		"name":"worm",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_worm_word.mp3"
	},
	{
		"image":"./imgs/zebra.png",
		"name":"zebra",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_zebra_word.mp3"
	},
	{
		"image":"./imgs/pigeon.png",
		"name":"pigeon",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_pigeon_word.mp3"
	},
	{
		"image":"./imgs/dinosaur.png",
		"name":"dinosaur",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_dinosaur_word.mp3"
	},
	{
		"image":"./imgs/dragon.png",
		"name":"dragon",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_dragon_word.mp3"
	},
	{
		"image":"./imgs/kangaroo.png",
		"name":"kangaroo",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_kangaroo_word.mp3"
	},
	{
		"image":"./imgs/clownfish.png",
		"name":"clownfish",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_clownfish_word.mp3"
	},
	{
		"image":"./imgs/rhinoceros.png",
		"name":"rhinoceros",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_rhinoceros_word.mp3"
	},
	{
		"image":"./imgs/toad.png",
		"name":"toad",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_toad_word.mp3"
	},
	{
		"image":"./imgs/puppy.png",
		"name":"puppy",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_puppy_word.mp3"
	},
	{
		"image":"./imgs/hippo.png",
		"name":"hippo",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_hippo_word.mp3"
	},
	{
		"image":"./imgs/rat.png",
		"name":"rat",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_rat_word.mp3"
	},
	{
		"image":"./imgs/ostrich.png",
		"name":"ostrich",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_ostrich_word.mp3"
	},
	{
		"image":"./imgs/peacock.png",
		"name":"peacock",
		"voice":"https://sound-wall.s3-eu-west-1.amazonaws.com/en_peacock_word.mp3"
	}
];

export var colorsArray = [
			{
				"image":"./img/colors/black.png"
			},
			{
				"image":"./img/colors/blue.png"
			},
			{
				"image":"./img/colors/brown.png"
			},
			{
				"image":"./img/colors/gray.png"
			},
			{
				"image":"./img/colors/green.png"
			},
			{
				"image":"./img/colors/magenta.png"
			},
			{
				"image":"./img/colors/orange.png"
			},
			{
				"image":"./img/colors/pink.png"
			},
			{
				"image":"./img/colors/purple.png"
			},
			{
				"image":"./img/colors/red.png"
			},
			{
				"image":"./img/colors/white.png"
			},
			{
				"image":"./img/colors/yellow.png"
			}
		
		];
		
		export var fruitsArray =[
		{
			"image" : "./img/fruits/apple.png"
		},
		{
			"image" : "./img/fruits/avocado.png"
		},
		{
			"image" : "./img/fruits/banana.png"
		},
		{
			"image" : "./img/fruits/cherry.png"
		},
		{
			"image" : "./img/fruits/chikoo.png"
		},
		{
			"image" : "./img/fruits/custardapple.png"
		},
		{
			"image" : "./img/fruits/grapes.png"
		},
		{
			"image" : "./img/fruits/guava.png"
		},
		{
			"image" : "./img/fruits/jackfruit.png"
		},
		{
			"image" : "./img/fruits/lime.png"
		},
		{
			"image" : "./img/fruits/mango.png"
		},
		{
			"image" : "./img/fruits/orange.png"
		},
		{
			"image" : "./img/fruits/papaya.png"
		},
		{
			"image" : "./img/fruits/peach.png"
		},
		{
			"image" : "./img/fruits/pear.png"
		},
		{
			"image" : "./img/fruits/pineapple.png"
		},
		{
			"image" : "./img/fruits/plum.png"
		},
		{
			"image" : "./img/fruits/pomegranate.png"
		},
		{
			"image" : "./img/fruits/strawberry.png"
		},
		{
			"image" : "./img/fruits/watermelon.png"
		}
		];
		export var shapesArray = [
			{
				"image":"./img/shape/circle.png"
			},
			{
				"image":"./img/shape/cone.png"
			},
			{
				"image":"./img/shape/cube.png"
			},
			{
				"image":"./img/shape/cylinder.png"
			},
			{
				"image":"./img/shape/decagon.png"
			},
			{
				"image":"./img/shape/ellipse.png"
			},
			{
				"image":"./img/shape/heart.png"
			},
			{
				"image":"./img/shape/heptagon.png"
			},
			{
				"image":"./img/shape/hexagon.png"
			},
			{
				"image":"./img/shape/octagon.png"
			},
			{
				"image":"./img/shape/parallelogram.png"
			},
			{
				"image":"./img/shape/pentagon.png"
			},
			{
				"image":"./img/shape/reclangularprism.png"
			},
			{
				"image":"./img/shape/rectangle.png"
			},
			{
				"image":"./img/shape/rhombus.png"
			},
			{
				"image":"./img/shape/righttriangle.png"
			},
			{
				"image":"./img/shape/square.png"
			},
			{
				"image":"./img/shape/star.png"
			},
			{
				"image":"./img/shape/trapezoid.png"
			},
			{
				"image":"./img/shape/triangle.png"
			},
			{
				"image":"./img/shape/circle.png"
			}
		];		
export var colorsArr = ["red","blue","green","white", "black","purple","pink","yellow"];